### ISSUE TITLE
Getting Authentication failed error

### ISSUE THREAD

**Issue by ananth10** [coresystemsFSM/android-twilio-video-with-service#5]
@FranziscaZarrai . Hi . finally i have set up local server :) . this is my local url

**https://b8b16824.ngrok.io/video-quickstart-php-master/token.php?username=ananth100**

Here i am passing username as identity . so i will get back token and identity . but when i opened app . displaying message like "Authentication failed" . but in this project default configuration type was PRODUCTIVE Then i modified this line   **sparkyClient = new SparkyClient(new SparkyConfiguration(SparkyConfiguration.TEST_LOCAL), TwilioUser.toAccessToken());** (for local server)

am i doing anything wrong?

**Comment by FranziscaZarrai** [comment]
Hey there and congratulations :) so basically if you use our sparky with this android project it should work. Just remember, that sparky requires certain JSON attributes (checkout your sparky log or add additional logs) - if you do not provide them in your request to sparky, then sparky will likely fail generating the token.

Also beware, that this android app here uses POST to communicate with sparky, not GET requests. Means our own sparky requires requests to be sent as POSTs. If i remember correctly the twilio demo servers used GET instead. So you won't get a sensible reply. Either change the requests in this project to GET (though for security reasons I'd recommend POST, so the parameters are not all listed in the URL) or change your server to expect POST requests.
