### ISSUE TITLE
When Caller calls, nothing happen

### ISSUE THREAD

**Issue by ra992** [coresystemsFSM/android-twilio-video-with-service#6]
This issue is regarding the scenario which I mentioned in https://github.com/twilio/video-quickstart-android/issues/73#issuecomment-291006027, however, there is no logs generated. and caller is not able to connect to callee.

**Comment by FranziscaZarrai** [comment]
@ra992 We do log in our application - if you could provide those logs for caller and callee from when you start the session till you call (and a little after that) that'd help in figuring out what kind of problem you're facing. Also - the person you're calling, is it actually the other device? You can see what device you are when on the invite view and looking at the field saying "current room"

**Comment by ra992** [comment]
I found this log file.
[log.txt](https://github.com/coresystemsFSM/android-twilio-video-with-service/files/909489/log.txt)

**Comment by FranziscaZarrai** [comment]
@ra992 Hey there, The logfile contains no logs from our application. At the minimum logs from TwilioChatService should be in there, but there are none. Same goes for SparkyClient - no logs from that class either. I did however find a log entry for a class called "MainActivity" - so i am guessing this is yours, which indicates you created your own project? Unfortunately we can't provide support for modified versions. So unless you're using this project here as-is it's near impossible for us to provide help.
